---
- name: Deploy Flask app
  hosts: web
  become: yes
  vars:
    app_name: my_flask_app
    virtualenv_dir: /opt/{{ my_flask_app}}/venv

  tasks:
  - name: Install required packages
    apt:
      name:
        - python3
        - python3-pip
    become: yes

  tasks:
  - name: Install virtualenv and python3-venv
    yum:
      name:
        - virtualenv
        - python3-venv

  - name: Create virtual environment
    command: python3 -m venv {{ virtualenv_dir }}

  - name: Activate virtual environment
    command: source {{ virtualenv_dir }}/bin/activate

  - name: Install Flask and other dependencies
    pip:
      requirements: requirements.txt

  - name: Deactivate virtual environment
    command: deactivate
