---
- name: Deploy Flask App
  hosts: web
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - virtualenv
          - python3-venv
        state: present
        update_cache: yes

    - name: git 
      command: python3 -m venv {{ virtualenv_dir }}

    - name: Activate virtual environment
      command: source {{ virtualenv_dir }}/bin/activate
      
    - name: Install Flask and other dependencies
      pip:
      requirements: "{{ app_dir }}/requirements.txt"

    - name: Deactivate virtual environment
      command: deactivate

...
