---
- name: Deploy Flask App
  hosts: server
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - virtualenv
          - python3-venv
        state: present
...
