---
- name: Deploy Flask appi
  hosts: web
  become: yes
  vars:
    app_name: app.py
    virtualenv_dir: /home/ubuntu/Flask-web-App/{{ app.py }}/venv
    
  tasks:
    - name: Install virtualenv and python3-venv
      apt:
        name:
          - virtualenv
          - python3-venv

    - name: create virtual environment
      command: virtualenv /home/ubuntu/virtualenv_dir

        #- name: create virtual environment
        #command: source /home/ubuntu/virtualenv_dir/bin/activate


    - name: Install Flask and other dependencies
      pip:
       name: flask
       state: present

          
    - name: Deactivate virtual environment
      command: deactivate
